spring.application.name=parking-microservice

server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/thesis_parking
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

spring.kafka.consumer.group-id=parking-service-group
spring.kafka.consumer.auto-offset-reset=earliest

kafka.topic.iot=parking.iot.occupancy
kafka.topic.cv=parking.cv.occupancy